#!/bin/bash
# Simple script to bypass the sandbox permission issue

echo "Running expo-configure-fix.sh"

# Create the ExpoModulesProvider.swift file directly
cat > "${PODS_ROOT}/Target Support Files/Pods-PaceMap/ExpoModulesProvider.swift" << 'EOF'
// This file is generated automatically. Do not edit manually.
// It will be overwritten during the next build.

import Foundation
import ExpoModulesCore

// Autogenerated provider for Expo modules
public class ExpoModulesProvider: ExpoModulesProviderProtocol {
  public func providers() -> [ModuleProvider] {
    return [
      // Expo modules
      ExpoModulesCore.AppDelegateSubscriberModuleProvider(),
      ExpoModulesCore.DevMenuModuleProvider(),
      ExpoAsset.AssetModuleProvider(),
      ExpoBlur.BlurModuleProvider(),
      ExpoConstants.ConstantsModuleProvider(),
      ExpoFileSystem.FileSystemModuleProvider(),
      ExpoFont.FontModuleProvider(),
      ExpoHaptics.HapticsModuleProvider(),
      ExpoKeepAwake.KeepAwakeModuleProvider(),
      ExpoLinearGradient.LinearGradientModuleProvider(),
      ExpoLinking.LinkingModuleProvider(),
      ExpoLocation.LocationModuleProvider(),
      ExpoSecureStore.SecureStoreModuleProvider(),
      ExpoSplashScreen.SplashScreenModuleProvider(),
      ExpoSystemUI.SystemUIModuleProvider(),
      ExpoWebBrowser.WebBrowserModuleProvider(),
    ]
  }
}
EOF

echo "Created ExpoModulesProvider.swift successfully"
exit 0 